services:
  - type: web
    name: meta-piqma-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://quyvxrcjjhamxhiidjbx.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_SEARCH_SERVER_URL
        value: https://meta-piqma-search.onrender.com
    staticPublishPath: dist
